### ISSUE TITLE
This mod reduces too much performance

### ISSUE THREAD

**Issue by Zouzs** [PigCart/particle-rain#35] opened 2024-04-16 21:51 UTC
I can figure out why this mod is naturally heavy and resource consuming but, i've seen that it doesn't force Minecraft to use more PC resources.

I got my framerate set on 70fps (stable) and when it starts raining it starts to flicker between 50fps and 40fps.

The weird thing it's that my GPU stays at 50% and my CPU at 20%. 

So far, reducing rain density has helped to get better performance.

**Comment by Zouzs** [comment] 2024-04-16 21:55
Weird, looks like it somehow makes my FPS unstable, so i just capped my fps at 90fps and now i'm getting 70fps.

Which, works for now, but it's not ideal.

**Comment by PigCart** [comment] 2024-06-22 17:07
duplicate of #17

**Closed by PigCart** 2024-06-22 17:07 UTC
